---
  - name: get ecs service details
      ecs_service_facts:
        cluster: "{{ cluster }}"
        service: "{{ short_name }}"
        details: true
      register: ecs_service_facts_output

  - set_fact:
      loadbalancers: "{{ ecs_service_facts_output.services[0].loadBalancers }}"
    when: ecs_service_facts_output.services | count

  - name: create or update ecs service using target group
    ecs_service:
      state: present
      name: "{{ short_name }}"
      cluster: "{{ cluster }}"
      task_definition: "{{ short_name }}"
      load_balancers: "{{ loadbalancers }}"
      desired_count: "{{ app_desired_count | default( 3 ) }}"
      deployment_configuration:
        minimum_healthy_percent: "{{ app_minimum_healthy | default( 100 ) }}"
        maximum_percent: "{{ app_maximum_percent | default( 200 )}}"