- name: Create task definition
  ecs_taskdefinition:
    family: nginx
    containers:
    - name: containername
      essential: true
      image: "ecrrepo/imagename"
      portMappings:
      - containerPort: 8080
        hostPort:      8080
    launch_type: FARGATE
    cpu: 512
    memory: 1024
    state: present
    network_mode: awsvpc